# Generated by Django 4.2.2 on 2023-06-30 20:04

from django.db import migrations, models
import django.db.models.deletion
import quiz_module.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فیلد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[quiz_module.validators.is_valid_iran_code], verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='شماره تلفن همراه')),
                ('image_file', models.FileField(upload_to='image_file', validators=[quiz_module.validators.validate_file_extension], verbose_name='فایل تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.quizfield', verbose_name='رشته انتخابی')),
            ],
        ),
    ]
