# Generated by Django 4.2.2 on 2023-06-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='field_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_field', to='quiz_module.quizfield', verbose_name='رشته انتخابی دوم'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='field_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_field', to='quiz_module.quizfield', verbose_name='رشته انتخابی سوم'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_field', to='quiz_module.quizfield', verbose_name='رشته انتخابی اول'),
        ),
    ]
