# Generated by Django 4.2 on 2023-07-03 16:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_module', '0004_quizoption_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ کاربران',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField(verbose_name='سوال اول')),
                ('question_2', models.TextField(verbose_name='سوال دوم')),
                ('question_3', models.TextField(verbose_name='سوال سوم')),
                ('question_4', models.TextField(verbose_name='سوال چهارم')),
                ('answer_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.quiz')),
            ],
            options={
                'verbose_name': 'سوالات آزمون',
                'verbose_name_plural': 'سوالات آزمون ها',
            },
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.AlterModelOptions(
            name='quizfield',
            options={'verbose_name': 'رشته', 'verbose_name_plural': 'رشته ها'},
        ),
        migrations.AlterModelOptions(
            name='quizsubscription',
            options={'verbose_name': 'ثبت نام آزمون', 'verbose_name_plural': 'ثبت نام های آزمون'},
        ),
        migrations.RemoveField(
            model_name='quizsubscription',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='quizsubscription',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='quizsubscription',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='quizsubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
