# Generated by Django 4.2.2 on 2023-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0005_quizanswer_quizquestion_delete_quizoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_4',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_1',
            field=models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز ', verbose_name='گزینه اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_2',
            field=models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز ', verbose_name='گزینه دوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_3',
            field=models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز ', verbose_name='گزینه سوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_4',
            field=models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز ', verbose_name='گزینه چهارم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(default='مار پایتون جه زنگی است', verbose_name='سوال'),
            preserve_default=False,
        ),
    ]
