# Generated by Django 4.2 on 2023-07-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz_module.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_module', '0006_remove_quizquestion_question_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('educational_field', models.CharField(choices=[('HS', 'دبیرستان'), ('VS', 'هنرستان')], max_length=2)),
                ('student_code', models.CharField(max_length=255, verbose_name='شماره دانش آموزی')),
                ('school_name', models.CharField(max_length=255, verbose_name='نام دبیرستان / هنرستان')),
                ('educational_stage', models.CharField(choices=[('tenth', 'دهم'), ('eleventh', 'یازدهم'), ('twelfth', 'دوازدهم')], max_length=10, verbose_name='مقطع تحصیلی')),
                ('parent_phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('image_file', models.FileField(upload_to='image_file', validators=[quiz_module.validators.validate_file_extension], verbose_name='فایل تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.ManyToManyField(to='quiz_module.quizfield', verbose_name='رشته های انتخابی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت نام آزمون',
                'verbose_name_plural': 'ثبت نام های آزمون',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255, verbose_name='نام دانشگاه')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('image_file', models.FileField(upload_to='image_file', validators=[quiz_module.validators.validate_file_extension], verbose_name='فایل تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizSubscription',
        ),
    ]
