# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0007_internsubscription_jobseekersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رشته')),
                ('english_title', models.CharField(max_length=255, verbose_name='عنوان انگلیسی رشته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رشته کارآموزی',
                'verbose_name_plural': 'رشته های کارآموزی',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رشته')),
                ('english_title', models.CharField(max_length=255, verbose_name='عنوان انگلیسی رشته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رشته کارجو',
                'verbose_name_plural': 'رشته های کارجو',
            },
        ),
        migrations.AddField(
            model_name='jobseekersubscription',
            name='fields',
            field=models.ManyToManyField(to='quiz_module.jobseekerfield', verbose_name='رشته های انتخابی'),
        ),
        migrations.AlterField(
            model_name='internsubscription',
            name='fields',
            field=models.ManyToManyField(to='quiz_module.internfield', verbose_name='رشته های انتخابی'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_module.internfield', verbose_name='رشته انتخابی اول'),
        ),
        migrations.DeleteModel(
            name='QuizField',
        ),
    ]
