# Generated by Django 4.2.2 on 2023-07-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_module', '0011_alter_internsubscription_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internsubscription',
            options={'verbose_name': 'ثبت نام کارآموز', 'verbose_name_plural': 'ثبت نام های کارآموز'},
        ),
        migrations.AlterModelOptions(
            name='jobseekersubscription',
            options={'verbose_name': 'ثبت نام کارجو', 'verbose_name_plural': 'ثبت نام های کارجو'},
        ),
        migrations.AddField(
            model_name='jobseekersubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
