# Generated by Django 4.2.2 on 2023-07-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'کد یبار مصرف',
                'verbose_name_plural': 'کدهای یبار مصرف',
            },
        ),
    ]
